### ISSUE TITLE
I use ngx.re.split(),but receive http 500.

### ISSUE THREAD

**Issue by wuyachao** [openresty/lua-resty-core#104]
example:
local ngx_re = require "ngx.re"
local res, err = ngx_re.split("c:574|576|20170424155217","|")

log:
lua entry thread aborted: memory allocation error: not enough memory

use another:

```
function split(str, split_char)
    local sub_str_tab = {};
    while (true) do
        local pos = string.find(str, split_char, 1, true);
        if (not pos) then
            sub_str_tab[#sub_str_tab + 1] = str;
            break;
        end
        local sub_str = string.sub(str, 1, pos - 1);
        sub_str_tab[#sub_str_tab + 1] = sub_str;
        str = string.sub(str, pos + 1, #str);
    end

    return sub_str_tab;
end
```
local res, err = split("c:574|576|20170424155217","|")
ngx.say(res[1])

result:
c:574

I do not know if I have used it correctly.

**Comment by thibaultcha** [comment]
@wuyachao Try escaping the `|`, like so: `"\\|"`. I will take a look at what went wrong exactly later today. Tanks for the report.

**Comment by wuyachao** [comment]
@thibaultcha  
```
local ngx_re = require "ngx.re"
local res, err = ngx_re.split("c:574|576|20170424155217","\\|")
```
Thanks for your suggestion，i can get the result correctly.

**Comment by thibaultcha** [comment]
@wuyachao Follow #106 for a discussion on the fix for this behavior.

**Comment by thibaultcha** [comment]
This has been taken care of by #106, which has been merged :)

**Comment by wuyachao** [comment]
@thibaultcha  thank you
