### ISSUE TITLE
[Feature Proposal] New API to get Nginx log_level

### ISSUE THREAD

**Issue by spacewander** [openresty/lua-resty-core#116]
It would be quite useful if we could get the configured `error_log` level via Lua code.
For instance, we could do something like this:
```lua
-- config.lua
_M.log_level = ngx.config.log_level()

-- req.lua
if log_level >= ngx.WARN then
    -- Now we save an `encode` operation if we configure error_log level to `error`.
    ngx.log(ngx.WARN, cjson.encode(obj), ...)
end
```
Currently, `ngx.log` handles the lua parameters only when the given level is higher than the configured one. And maybe we don't need to care about those log levels higher than `debug` in Lua land. So what we need to do is just extracting some existent code into a new function.

Here is a question: since we could implement this feature in a separate Nginx C module, will you still accept it as a part of OpenResty's feature list?

**Comment by agentzh** [comment]
@spacewander We can do this in the `ngx.errlog` module of this library. The corresponding C API could be in the `ngx_lua` core. Pull requests are welcome! Thanks!
