### ISSUE TITLE
Feature Request:Dynamicly Add/Delete upstream  groups

### ISSUE THREAD

**Issue by noname007** [openresty/lua-resty-core#121]
from https://github.com/openresty/lua-upstream-nginx-module/issues/1, i found this https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/balancer.md.
but this still not implement  the feature add/delete upstream by lua code to have more flexible 。

do you have planed to do this?

**Comment by agentzh** [comment]
@noname007 balancer_by_lua* supports dynamic upstream peering on the *request* level? What better flexibility can you expect than this?

**Comment by noname007** [comment]
i want to proxy diffrent request to the diffrent upstream groups by some request  info. So i can  still use the upstream healthcheck to monitor the upstream server running conditions.
@agentzh

**Comment by noname007** [comment]
o, i understood. the balancer have had the ability to do this.
