### ISSUE TITLE
a question about balancer.set_more_tries() when proxy_next_upstream_tries set to 0

### ISSUE THREAD

**Issue by jils2013** [openresty/lua-resty-core#136]
When proxy_next_upstream_timeout set to 0(default),nginx will try all upstream servers;
When proxy_next_upstream_timeout set to 0(default),using balancer.set_more_tries(x>0) will get "reduced tries due to limit",then stop trying;
Here balancer.set_more_tries() seems not to do what we want？

**Comment by spacewander** [comment]
Maybe your problem is duplicated with #90.

**Comment by jils2013** [comment]
@spacewander,yes...thank you,i will try the latest branch;
