### ISSUE TITLE
typo fix

### ISSUE THREAD

**Issue by aifeiasdf** [openresty/lua-resty-core#137]
https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/balancer.md#get_last_failure

Retrieves the failure details about the previous failed attempt (if any) when the next_upstream retrying mechanism is in action. When there was indeed a failed previous attempt, it returned a string `descrbing`->`describing` that attempt's state name, as well as an integer describing the status code of that attempt.

**Comment by agentzh** [comment]
@aifeiasdf Fixed in master. Thanks!
