### ISSUE TITLE
Sometimes ssl.server_name() may returns nil value

### ISSUE THREAD

**Issue by hololoev** [openresty/lua-resty-core#138]
Hello.
It's possible not a bug, but it's our current problem.

Sometimes, about 1 of 1000 requests has an error in this function. As I understood on this line: https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/ssl.lua#L160 Because there is no error string returns.

Of course part of these errors can be fired by really wrong requests. But yesterday we have checked with 100% trusted request (from yandex money), and problem really exists. Part of request from ya.money comes to one listen IP and has no problem, and part comes to another IP and has this problem. The nginx config is the same for both.

Is there any way to check what's wrong? And also are there any nginx options can affect on this code?

**Comment by agentzh** [comment]
@hololoev Are you 100% sure the problematic SSL connection indeed provides an SNI name? The line number you referenced is clearly for the case that there is no SNI name present in the SSL client's request packet.

**Comment by agentzh** [comment]
@hololoev To support those older SSL clients with no SNI support, you have to use different server IP addresses for each different SSL domains. There is just no other way around this.

**Comment by hololoev** [comment]
@agentzh I'm sure on 100%, but I'm not sure that it's a bug. Mb we do something wrong. So, right now we have 2 different servers. Old one uses typical nginx scheme - one config file for one client.

Like: 

```
{
server_name ...
cert ...
key ...
...
etc
}
```

And new one uses lua ssl cert management. The part of this manager is:

```
local ssl = require('ngx.ssl')

local rawServerName, snerr = ssl.server_name() -- error here
if rawServerName == nil then
  ngx.log(ngx.ERR, "LUA-SSL-ERR rawServerName is nil. " .. inspect(snerr) ) -- snerr is nil too
  return ngx.exit(405)
end
```

The old is working fine. And as I understand it means that all necessary headers are present in request. But new (only for yamoney and only for several IPs) doesn't. Old and new servers use the same IPs.

The same lua ssl manager works with about 2000 different websites, but we have a problem only with several.

Is there a way to dig deeper?

**Comment by agentzh** [comment]
@hololoev It's not the Host HTTP request header at all. It is the TLS extension SNI. It's completely normal for an SSL client to not use this TLS extension or jut not provide the SNI name.

The only way to be 100% sure is to inspect the SSL client_hello packets directly.
