### ISSUE TITLE
balancer.lua  can use hash or weight rout

### ISSUE THREAD

**Issue by sdcuike** [openresty/lua-resty-core#16]
Can I user balancer.lua by hash or weight rout to rout server.

**Comment by agentzh** [comment]
@sdcuike We are currently working on a Lua library that implements such balancers in Lua and C for the context of `balancer_by_lua` (we cannot directly NGINX's own balancing implementations since they are static while here we are very dynamic).

**Comment by sdcuike** [comment]
Get, Thank you !
