### ISSUE TITLE
ngx.semaphore experimental?

### ISSUE THREAD

**Issue by kmchipower** [openresty/lua-resty-core#203]
Hello, we are looking to use ngx.semaphore for a fairly large undertaking.  I noticed that the documentation says that the module is considered experimental.  Is this still the case?

**Comment by thibaultcha** [comment]
Hi,

Closing this, as the status of this module has been updated to production ready for some time now: https://github.com/openresty/lua-resty-core/commit/bdbac701eb017370775f7333979922041021aeee
