### ISSUE TITLE
segfault when base64url decoding invalid data

### ISSUE THREAD

**Issue by bjne** [openresty/lua-resty-core#232]
```
nginx version: openresty/1.15.8.1rc0
built by gcc 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04)
built with OpenSSL 1.1.0j  20 Nov 2018
TLS SNI support enabled
```
I am experiencing random segfaults when passing invalid data to base64url (and base64 in general seems)
This seems to be caused by a race condition of some sorts, since adding some debugging in ngx.base64
sometimes makes the problem disappear.

Minimal test to reproduce:

```lua
local u64d = require "ngx.base64".decode_base64url

for i=1,1000 do
        local x = u64d(("x"):rep(i))
end
```
```
$ resty segfault.lua ; echo $?
0
$ resty segfault.lua ; echo $?
139
```

**Comment by agentzh** [comment]
@bjne Thanks for the report and the minimal test case! I can reproduce it on my side, though as you have noted, not always. I've prepared a patch which should fix this. No longer reproducible on my side. Will you try the patch on your side as well? Many thanks!

See https://github.com/openresty/lua-resty-core/pull/233/files

**Comment by agentzh** [comment]
The test case will be committed to resty-cli's test suite since it is not reproducible in lua-resty-core's test suite's execution context. Alas.

**Comment by bjne** [comment]
Thanks @agentzh, works great! I should have seen this.

**Comment by thibaultcha** [comment]
Here is the LuaJIT fix for this issue: https://github.com/openresty/luajit2/pull/46
