### ISSUE TITLE
nginx 1.16.0重启提示缺少文件

### ISSUE THREAD

**Issue by natural-ts** [openresty/lua-resty-core#248]
[root@iZwz9avyv2945ilt432lffZ wwwroot]# lnmp nginx restart
+-------------------------------------------+
|    Manager for LNMP, Written by Licess    |
+-------------------------------------------+
|              https://lnmp.org             |
+-------------------------------------------+
Stoping nginx...  done
Starting nginx... nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
        no field package.preload['resty.core']
        no file './resty/core.lua'
        no file '/usr/local/share/luajit-2.1.0-beta3/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core/init.lua'
        no file './resty/core.so'
        no file '/usr/local/lib/lua/5.1/resty/core.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so')
 done
[root@iZwz9avyv2945ilt432lffZ wwwroot]#

**Comment by spacewander** [comment]
See https://github.com/openresty/lua-nginx-module/pull/1501.

**Comment by thibaultcha** [comment]
Please use an official OpenResty release, or avoid using RCs of the ngx_lua module. Or if you do, make sure to have a close look at the changes and new documentation before doing so. For now, you can disable the loading of the `resty.core` module, but in future releases, the CFunction API will be removed in favor of the FFI based API and `resty.core` will become mandatory. 

Thanks

**Comment by natural-ts** [comment]
> 请使用官方OpenResty版本，或避免使用ngx_lua模块的RC。或者如果您这样做，请确保在执行此操作之前仔细查看更改和新文档。目前，您可以禁用`resty.core`模块的加载，但在将来的版本中，将删除CFunction API以支持基于FFI的API，并且`resty.core`将成为强制性的。
> 
> 谢谢

alright, thank you very much

**Comment by xuebinshushu** [comment]
谢谢！我用lua-nginx-module-0.10.14.tar.gz + luajit2-2.1-20190912解决了！

**Comment by zhiwu88** [comment]
> 
> 
> 谢谢！我用lua-nginx-module-0.10.14.tar.gz + luajit2-2.1-20190912解决了！

意思是使用  lua-nginx-module-0.10.15  不行才会报这个错？

**Comment by xuebinshushu** [comment]
> > 谢谢！我用lua-nginx-module-0.10.14.tar.gz + luajit2-2.1-20190912解决了！
> 
> 意思是使用 lua-nginx-module-0.10.15 不行才会报这个错？

是的，不知道更新了啥。

**Comment by zhiwu88** [comment]
> 
> 
> > > 谢谢！我用lua-nginx-module-0.10.14.tar.gz + luajit2-2.1-20190912解决了！
> > 
> > 
> > 意思是使用 lua-nginx-module-0.10.15 不行才会报这个错？
> 
> 是的，不知道更新了啥。

Good，确实如此。

**Comment by hereTac** [comment]
> 谢谢！我用lua-nginx-module-0.10.14.tar.gz + luajit2-2.1-20190912解决了！

It is the right way!!!
