### ISSUE TITLE
lua-nginx-module built with Nginx 1.11 doesn't provide symbol 'ngx_http_lua_ffi_shdict_free_space'

### ISSUE THREAD

**Issue by spacewander** [openresty/lua-resty-core#251]
People see the error message below:
`[error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: ...lua-resty-core/lib/resty/core/shdict.lua:84: /opt/luajit21/lib/libluajit-5.1.so.2: undefined symbol: ngx_http_lua_ffi_shdict_free_space)`

We should detect if the symbol `ngx_http_lua_ffi_shdict_free_space` exists.

**Comment by agentzh** [comment]
Yeah, we should guard such symbols which may be missing.

**Comment by thibaultcha** [comment]
PR submitted at #255
