### ISSUE TITLE
per domain ssl handle

### ISSUE THREAD

**Issue by mehrdadpfg** [openresty/lua-resty-core#281]
Hello dear Agentzh,

I was wondering how I can process per domain certificate when the access_by_lua is called after the ssl_by_lua and I can not access ngx domain name

does it need any Nginx patches or it can be handled by Lua itself?

any solutions?

**Comment by Ara4Sh** [comment]
same issue here 
for example you cant access ngx.var.http_host in order to detect the domain and load the write certificate.
