### ISSUE TITLE
nginx: [warn] lua_load_resty_core is deprecated (the lua-resty-core library is required since ngx_lua v0.10.16) in /usr/local/nginx/conf/nginx.conf:34 nginx: [alert] failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: 

### ISSUE THREAD

**Issue by mgltech** [openresty/lua-resty-core#285]
nginx: [warn] lua_load_resty_core is deprecated (the lua-resty-core library is required since ngx_lua v0.10.16) in /usr/local/nginx/conf/nginx.conf:34
nginx: [alert] failed to load the 'resty.core' module (https://github.com/openresty/lua-resty-core); ensure you are using an OpenResty release from https://openresty.org/en/download.html (reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file '/usr/local/lib/lua//resty/core.lua'
	no file './resty/core.lua'

**Comment by agentzh** [comment]
@mgltech You should follow the suggestion and use OpenResty instead. Otherwise you'll have to make sure the correct version of lua-resty-core is installed. The error message you provided already explains it well.
