### ISSUE TITLE
balancer_by_lua_file ignores lua_code_cache setting ?

### ISSUE THREAD

**Issue by filipslavik** [openresty/lua-resty-core#29]
Hi,

I'm testing the ``ngx.balancer`` module and I believe the ``lua_code_cache`` directive is being ignored ? 

I have the following backend configuration : 

```nginx

http {
 
  lua_code_cache off;
  upstream backend {
      server 127.0.0.1; 
      balancer_by_la_file my_balancer.lua;
  }

}
```

Code changes in the ``my_balancer.lua`` file are reflected only when I restart nginx. Other blocks, like for example ``content_by_lua_file`` are working as expected (no restart required).

I'm testing all this on a fresh 1.9.7.3 OpenResty installation.

**Comment by agentzh** [comment]
@filipslavik This issue has already been fixed in the git master branch of lua-nginx-module via the following commit:

https://github.com/openresty/lua-nginx-module/commit/6ba92a67

**Comment by filipslavik** [comment]
Aha! Thank you for that.
