### ISSUE TITLE
Two-way SSL can not working!

### ISSUE THREAD

**Issue by TimWangs** [openresty/lua-resty-core#294]
Hi 
I have some questions
We need to implement two way SSL with OpenResty, now my config file is 

        server {
		listen 443 ssl;
		server_name localhost;
				
		location / {
			proxy_pass http://localhost:8443;
		}
		
		ssl_certificate     D://cert/server.cer;
		ssl_certificate_key D://cert/server.key;

        server_tokens off;
		ssl_certificate_by_lua_block {
		
			local ssl = require "ngx.ssl"
		
			ngx.log(ngx.ERR, ssl.server_name())
			
			
			
			local certificate = io.open("D://cert/client.cer", "r")
			local data = certificate:read("*all")
			certificate.close()
			
			der_cert_chain, err = ssl.cert_pem_to_der(data)
			if not der_cert_chain then
				ngx.log(ngx.ERR, "failed to cert_pem_to_der: ", err)
				return
			end
			
			ok, err = ssl.set_der_cert(der_cert_chain)
			if not ok then
				ngx.log(ngx.ERR, "failed to set_der_cert ", err)
				return
			end
			
		}
		
	}

but it's not working,my chrome response `This site can’t provide a secure connection`
how should i do?

**Comment by doujiang24** [comment]
@TimWangs you mean "client certificate authentication", right?

it's still in a PR, welcome to test it on your side.

**Comment by TimWangs** [comment]
@doujiang24 right, How do i configure？

**Comment by doujiang24** [comment]
@TimWangs you need to rebuild the openresty by using the PRs and follow the usage documented in the PRs.

**Comment by TimWangs** [comment]
@doujiang24 我还是说中文吧，那个方式太麻烦了，我目前想了个办法是通过自签名证书生成二级证书，服务端的client cert使用自签名证书的public key，客户端使用二级证书 privete key，可以通过验证吗？我目前进行的有点困难

**Comment by doujiang24** [comment]
@TimWangs 
we prefer English in github issue, you are welcome to use Chinese in OpenResty Forum:
https://forum.openresty.us/t/zh-discussion

for your question, it shouldn't work, the public key and private key should be paired on the same side.

**Comment by TimWangs** [comment]
Thanks, I found a way
