### ISSUE TITLE
something related to the last "ngx.semaphore" commit ?

### ISSUE THREAD

**Issue by chipitsine** [openresty/lua-resty-core#36]
have a look, it fails with something related to semaphores:

https://travis-ci.org/chipitsine/lua-resty-core/builds/128364836

```
ok 162 - TEST 1: clear certs - pattern "[emerg]" does not match a line in error.log (req 1)

WARNING: TEST 1: clear certs - 2016/05/06 18:15:59 [crit] 25576#0: *4 SSL_shutdown() failed (SSL: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init), client: 127.0.0.1, server: localhost, request: \"GET /t HTTP/1.1\", host: \"localhost\" at /usr/local/share/perl/5.18.2/Test/Nginx/Socket.pm line 1192.

ok 163 - TEST 14: ngx.semaphore in ssl_certificate_by_lua* - status code ok

not ok 164 - TEST 14: ngx.semaphore in ssl_certificate_by_lua* - response_body - response is expected (req 0)

#   Failed test 'TEST 14: ngx.semaphore in ssl_certificate_by_lua* - response_body - response is expected (req 0)'

#   at /usr/local/share/perl/5.18.2/Test/Nginx/Socket.pm line 1277.

# @@ -1,2 +1,2 @@

#  connected: 1

# -ssl handshake: boolean

# +failed to do SSL handshake: handshake failed

not ok 165 - TEST 14: ngx.semaphore in ssl_certificate_by_lua* - grep_error_log_out (req 0)

```

**Comment by agentzh** [comment]
@chipitsine It looks like your OpenSSL library is just too new for the nginx core. Only recent nginx cores (1.9.12+) can handle the new changes in OpenSSL 1.0.2f or later properly.

Also, ensure you also have the nginx core patch from OpenResty for the `ssl_certificate_by_lua*` feature.

**Comment by chipitsine** [comment]
I compile nginx --with-openssl=${TRAVIS_BUILD_DIR}/openssl-1.0.2XXX
however, Test::Nginx, I guess is linked against openssl-1.0.1,could it be an issue ?

ok, I'll have a look at those patches.
btw, lua-resty-core is missing util/build.sh, I've no idea how to compile it properly

**Comment by agentzh** [comment]
@chipitsine lua-resty-core is pure Lua. There's no need to add a build.sh script for it. It usually just uses the lua-nginx-module's build. See

https://github.com/openresty/opsboy/blob/master/samples/ortest-ec2.ob.tt

for how lua-resty-core runs its tests on my EC2 test cluster.

**Comment by agentzh** [comment]
@chipitsine `--with-openssl=PATH` always uses static linking. I don't see how you can later link against a different version of OpenSSL libraries.

**Comment by thibaultcha** [comment]
Considering this answered.
