### ISSUE TITLE
2022/06/14 05:43:28 [error] 159#0: *45 lua entry thread aborted: runtime error: /opt/nginx/lib/lua/resty/core/misc.lua:178: /usr/local/lib/libluajit-5.1.so.2: undefined symbol: ngx_http_lua_ffi_req_is_internal stack traceback: coroutine 0: [C]: in function '__index' /opt/nginx/lib/lua/resty/core/misc.lua:178: in function 'is_internal' /opt/nginx/scripts/manage_access_session.lua:70: in main chunk, client: 10.221.16.1

### ISSUE THREAD

**Issue by vkhulbey** [openresty/lua-resty-core#397]
Using openresty with Nginx-1.22.
LuaJit, version-2.1
lua-nginx-module-0.10.21

**Comment by vkhulbey** [comment]
> Please use [luajit2](https://github.com/openresty/luajit2), not lua 5.1.

We are already using LuaJit-2(http://github.com/openresty/luajit2.git).

**Comment by vkhulbey** [comment]
Here is a small code snippet.

if not ngx.req.is_internal() then
  local access_control = ngx.shared.access_control

This call goes to **function ngx.req.is_internal()** in /lib/resty/core/misc.lua and it fails at line 178 during the call to  local **rc = C.ngx_http_lua_ffi_req_is_internal(r)**

**Comment by vkhulbey** [comment]
We are using lua-nginx-nodule-0.10.21.

Another point that I observed in **[ngx_http_lua_misc](https://github.com/openresty/lua-nginx-module/blob/0.10.21.x/src/ngx_http_lua_misc.c).c** is that **ngx_http_lua_ngx_req_is_internal** function is not present in 0.10.21.x branch whereas it is present in [master ](https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_misc.c)branch.

**Comment by vkhulbey** [comment]
@cppcoffee 
Another observation that I made:

ngx_http_lua_ffi_req_is_internal method is present in **master**/src/ngx_http_lua_misc.c whereas it's missing in **0.10.21.x**/src/ngx_http_lua_misc.c

**Comment by vkhulbey** [comment]
> openresty

We are getting lua-resty-core from https://github.com/openresty/lua-resty-core which I assume will fetch us the latest version.
With this, we are using lua-nginx-module version 0.10.21.

**Comment by zhuizhuhaomeng** [comment]
you need to use both the latest version of lua-resty-core and lua-nginx-module.

**Comment by vkhulbey** [comment]
> lua-resty-core and lua-nginx-module.

We are already on lua-nginx-module -0.10.21.
For lua-resty-core, should we take it from https://github.com/openresty/lua-resty-core or https://openresty.org/en/download.html?

**Comment by vkhulbey** [comment]
> you need to use both the latest version of lua-resty-core and lua-nginx-module.

Can you please confirm the latest version for lua-resty-core. Is it v0.1.23 ?

**Comment by zhuizhuhaomeng** [comment]
both from github master branch or both from the latest tag works.

**Comment by vkhulbey** [comment]
The issue was resolved after using both from the latest release tag.
Hence, closed this ticket.
