### ISSUE TITLE
Balancer/redis issues

### ISSUE THREAD

**Issue by craigp** [openresty/lua-resty-core#41]
I'm a little confused about requiring some modules. I was using the latest OpenResty bundle, and while working with it I found I could use `require "redis"` but not `require "resty.redis"` as documented, and `require "ngx.balancer"` doesn't work no matter what I do. Please advise.

**Comment by craigp** [comment]
Ok, I seem to have been able to fix my issue by changing:

`lua_package_path "/opt/openresty/lualib/resty/?.lua";`

.. which is the default, to:

`lua_package_path "/opt/openresty/lualib/?.lua;;";`

(Might be worth documenting that somewhere, unless I missed it, caused me a ton of frustration)

**Comment by agentzh** [comment]
@craigp You don't need to use `lua_package_path` since those libraries are always visible in the default search paths. "/opt/openresty/lualib/resty/?.lua" is the wrong search path. Always use the one in the documentation. Also the documentation already says that you don't need that if you are using the OpenResty bundle. Lua search paths are documented in the Lua 5.1 reference manual:

http://www.lua.org/manual/5.1/manual.html#pdf-package.loaders

**Comment by craigp** [comment]
Cool thanks. When I installed OpenResty it had `lua_package_path "/opt/openresty/lualib/resty/?.lua";` in there already, will remove it in future.

**Comment by agentzh** [comment]
@craigp Are you sure you are using the official OpenResty distribution? See

http://openresty.org/en/download.html

I'm pretty sure the official distribution's nginx.conf does not have that wrong directive.

**Comment by agentzh** [comment]
@craigp Whatever 3rd-party OpenResy distribution you are currently using, I suggest you contact the maintainer of that distribution to fix the problem in their nginx.conf.

**Comment by craigp** [comment]
yup, downloaded the official. Anyway, no big deal. If I have time tomorrow I'll do an install from scratch to confirm that it does the same.

**Comment by agentzh** [comment]
@craigp The official OpenResty distribution ships the official nginx distribution's `nginx.conf`. So there's no way that you see any ngx_lua specific configurations like `lua_package_path`. No way :)

**Comment by craigp** [comment]
Yeah, no worries man, I was scrambling to get things to work and taking bad advice from IRC, so I likely put that in there and didn't remember ;)
