### ISSUE TITLE
ssl_certificate_by_lua valid in http{}

### ISSUE THREAD

**Issue by alubbe** [openresty/lua-resty-core#42]
I just noticed that the below code is valid but throws a lot of runtime errors, incl. segfaults.
From the docs, ssl_certificate_by_lua should not be valid in http{}, only in server{}, right?
```nginx
http {
    ssl_certificate_by_lua_block { print("hello") }
    server {
        listen 443 ssl;
    }
}
```
Two sample errors:
```
SSL_do_handshake() failed (SSL: error:140A1175:SSL routines:ssl_bytes_to_cipher_list:inappropriate fallback) while SSL handshaking

worker process 45145 exited on signal 11 (core dumped)
```

**Comment by agentzh** [comment]
@alubbe Thanks for the report! Just fixed in the git master branch.
