### ISSUE TITLE
why the lua version number is commented out in Makefile

### ISSUE THREAD

**Issue by lynch1981** [openresty/lua-resty-core#449]
Can someone explain why the lua version number is commented out in Makefile?
I think it would be better if we keep it

> OPENRESTY_PREFIX=/usr/local/openresty
> 
> #LUA_VERSION := 5.1
> PREFIX ?=          /usr/local
> LUA_INCLUDE_DIR ?= $(PREFIX)/include
> LUA_LIB_DIR ?=     $(PREFIX)/lib/lua/$(LUA_VERSION)
> 	@@ -12,9 +13,11 @@ all: ;
>

**Comment by zhuizhuhaomeng** [comment]
We don't know the reason. It was changed in commit dbc9b6fd.

**Comment by lynch1981** [comment]
I saw someone reporting this failure, keeping LUA_VERSION would make it easier for them to install ngx_lua.
`nginx: [alert] failed to load the 'resty.core' module`

**Comment by zhuizhuhaomeng** [comment]
As long as ci stays through, we can uncomment it.

**Comment by zhuizhuhaomeng** [comment]
merged with small modification, please check the lastest master code.
