### ISSUE TITLE
Problems when the hostname is not an ip but a name defined in /etc/hosts (Docker)

### ISSUE THREAD

**Issue by ruslantalpa** [openresty/lua-resty-core#45]
Given this config for upstream
```
upstream postgrest {
        server remotecomputer:3000;
        balancer_by_lua_block {
            local balancer = require 'ngx.balancer'
            local host = 'remotecomputer'
            local port = 3000
            local ok, err = balancer.set_current_peer(host, port)
            if not ok then
                ngx.log(ngx.ERR, 'failed to set the current peer ', err)
                return ngx.exit(500)
            end
        }
        keepalive 64;
}
```

I get the error
```
2016/06/13 10:47:54 [error] 5#5: *1 [lua] balancer_by_lua:8: failed to set the current peer no host allowed while connecting to upstream, client: 192.168.99.1, server: localhost, request: "GET /.... HTTP/1.1", host: "192.168.99.100:8080"
```

If i comment the whole `balancer_by_lua_block` everything works

Any idea what i'm doing wrong? 
Thank you

**Comment by agentzh** [comment]
@ruslantalpa I think the error message you are getting is already quite clear about the reason: `set_current_peer` does not support host names other than IP addresses. You can use the `lua-resty-dns` library in an earlier phase, like `access_by_lua*`, to resolve your domain names to IP addresses and save the IP addresses to `ngx.ctx` which can be later read in your `balancer_by_lua*`.

**Comment by agentzh** [comment]
@ruslantalpa Oh, BTW, `/etc/hosts` is not supported (yet) in `lua-resty-dns`. So you'd better read that file yourself instead (but ensure you are caching the result otherwise reading a file upon every request can be quite expensive).

**Comment by ruslantalpa** [comment]
That's the answer i was looking for, to make sure it's a limitation and not me doing something wrong.
Thank you.

**Comment by sempasha** [comment]
`lua-resty-dns` seems to be too complex for simple dns lookup. And there is no ``/etc/hosts` file support at all.

Is there any way to use something like nginx build in [`ngx_inet_resolve_host`](https://github.com/nginx/nginx/blob/master/src/core/ngx_inet.h#L121) function?

**Comment by agentzh** [comment]
@ruslantalpa Well, you can abstract out a simple Lua function atop `lua-resty-dns` for simple queries and you can parse `/etc/hosts` in Lua rather easily.
