### ISSUE TITLE
runtime error: /usr/local/openresty/lualib/ngx/semaphore.lua:129: attempt to perform arithmetic on a nil value

### ISSUE THREAD

**Issue by ali-mahdavi-mehr** [openresty/lua-resty-core#457]
``lua user thread aborted:
runtime error: /usr/local/openresty/lualib/ngx/semaphore.lua:129: attempt to perform arithmetic on a nil value``

We have encountered this error in APISIX, and we are unsure when it occurs. Additionally, we do not know which library calls this function, but an error has occurred for us occasionally, not always. Please let us know the reason for this error and how to prevent it. Thank you

**Comment by tzssangglass** [comment]
> , and we are unsure when it occurs. Additionally, we do not know which library calls this function, but an error has occurred for us occasionally, not always. Please let us know the reason for this error and how to prevent it. Thank you

pls submit this issue to APISIX, not here.
