### ISSUE TITLE
Question:Is it safe to include latest lua-resty-code with 1.9.15.1 resty bundle?

### ISSUE THREAD

**Issue by rohitjoshi** [openresty/lua-resty-core#50]
`balancer_by_lua` in the latest code has support for connect / read timeout.  Is it safe to replace `lua-resty-core-0.1.6` version with latest code or should I just replace `lib/ngx/balancer.lua` file?

**Comment by agentzh** [comment]
You should replace both ngx_lua and Lua-resty-core to their latest git master versions as a whole at the same time. It's a bad idea to replace just individual files since you might miss stuff.
