### ISSUE TITLE
 cannot yield in sess get cb: missing async sess get cb support in OpenSSL

### ISSUE THREAD

**Issue by llg-java** [openresty/lua-resty-core#55]
when i compile the nginx with the new ssl_session branch and implement  sesion_fetch_by_lua
i got the error    cannot yield in sess get cb: missing async sess get cb support in OpenSSL

sysinfo: Linux version 3.10.0-123.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) #1 SMP Mon Jun 30 12:09:22 UTC 2014

**Comment by weihaitong** [comment]
me too

**Comment by agentzh** [comment]
@weihaitong It's officially documented:

https://github.com/openresty/lua-nginx-module#ssl_session_fetch_by_lua_block

To quote:

> If you are using the official pre-built packages for OpenResty 1.11.2.1 or later, then everything should work out of the box.
> 
> If you are using OpenSSL libraries not provided by OpenResty, then you need to apply the following patch for OpenSSL 1.0.2h or later:
> 
> https://github.com/openresty/openresty/blob/master/patches/openssl-1.0.2h-sess_set_get_cb_yield.patch
> 
> If you are not using the NGINX core shipped with OpenResty 1.11.2.1 or later, then you need to apply the following patch to the standard NGINX core 1.11.2 or later:
> 
> http://openresty.org/download/nginx-1.11.2-nonblocking_ssl_handshake_hooks.patch
>
