### ISSUE TITLE
configure error :  no lua-resty-core/config was found

### ISSUE THREAD

**Issue by cloudtrends** [openresty/lua-resty-core#57]
hi all , 

I am now using nginx , and want compile  lua-resty-core into nginx , by using below command 

 ./configure --prefix=/...../nginx \
         --with-ld-opt="-Wl,-rpath,/....../luagit210b2/lib" \
         --add-module=/.../ngx_devel_kit-0.3.0 \
         --add-module=/.../lua-nginx-module-0.10.6 \
         --add-module=/.../lua-upstream-nginx-module \
         --add-module=/..../lua-resty-core

but there are error happend:

./configure: error: no /..../config was found

btw,  I am using   git clone git@github.com:openresty/lua-resty-core.git  to get the lua-resty-core  code .

Thanks all .

**Comment by agentzh** [comment]
@cloudtrends `--add-module` option is for including NGINX C modules instead of Lua libraries, obviously. This is a Lua library.

**Comment by umarmughal824** [comment]
I am facing that error now. How to solve it? Didn't find any solution comment in this thread.
