### ISSUE TITLE
regex is not jit enabled

### ISSUE THREAD

**Issue by rshriram** [openresty/lua-resty-core#61]
I apologize if this is the wrong repo (please point me to the correct one where I can raise this issue).

When I profile open resty with the nginx-systemtap-toolkit tools, especially the ngx-pcrejit tool, it tells me that PCRE JIT is not enabled. 

```bash
root@myhost:~/nginx-systemtap-toolkit# ./ngx-pcrejit -p 6018
Tracing 6018 (/usr/sbin/nginx)...
Hit Ctrl-C to end.
^C
ngx_http_lua_ffi_exec_regex: 0 of 225968 are PCRE JITted.
ngx_http_regex_exec: 0 of 112985 are PCRE JITted.

Looks like JIT support is missing in your PCRE build.
```

However, I have enabled pcre jit support. I used the standard build script from [docker-openresty/trusty](https://github.com/openresty/docker-openresty/blob/master/trusty/Dockerfile)
wherein I enabled `--with-pcre` and `--with-pcre-jit`. The nginx config also shows that pcre jit is enabled.

Am I supposed to enable something else for jit compiling PCRE regexes?
I even tried the nginx directive `pcre_jit on;`. No use.

Am I missing something?

**Comment by rshriram** [comment]
Flamegraph points to `pcre_exec` instead of pcre_jit_exec.
![image](https://cloud.githubusercontent.com/assets/8202871/19134877/c2e9e544-8b2e-11e6-95b0-50f6972ad221.png)

**Comment by agentzh** [comment]
Have you specified the "jo" options string when calling the ngx.re.* API functions?

**Comment by rshriram** [comment]
"j" is new to me. So, I tried with "jo". I can now see pcre_jit_exec in the flame graphs. 
But the ngx-pcrejit is still reporting that none of the regexps were jit compiled.
I still get the same output saying looks like pcre jit is not enabled.

I also verified that the pcre Makefile has the -g flag.

**Comment by agentzh** [comment]
@rshriram Try enabling the debug logs temporarily and see if the PCRE JIT compilation just fails for some reason.

**Comment by agentzh** [comment]
@rshriram Just re-compile with `--with-debug` and configure `error_log logs/error.log debug;` in your `nginx.conf`. It would be much easier when the official OpenResty deb packages for Ubuntu are ready (which should be out soon). Then you can just install the `openresty-debug` package via `apt get` and start `openresty-debug` to run your OpenResty applications.

**Comment by agentzh** [comment]
@rshriram Oh, BTW, your `ngx-pcrejit` tool reports that it is tracing the `/usr/sbin/nginx` process. Is that truly OpenResty's nginx? I know nothing about the openresty-docker image BTW.

**Comment by agentzh** [comment]
@rshriram Because you are seeing `pcre_jit_exec` in the flame graphs, it means that your PCRE JIT compilation already succeeds. Maybe it's just that `ngx-pcrejit` does not work with recent versions of PCRE any more. It was created a while ago.

**Comment by agentzh** [comment]
@rshriram I just tried the latest PCRE 8.39 on my side with OpenResty. And `ngx-pcrejit` works properly on the following `nginx.conf` snippet:

```nginx
    location ~ '^/t' {
        content_by_lua_block {
            ngx.say(ngx.re.find(ngx.var.uri, [[\w]], "jo"))
        }
    }
```

Running `curl localhost:8080/t` while the `ngx-pcrejit` tool yields the following output of the latter:

```console
$ ./ngx-pcrejit -p `pgrep -f 'nginx: worker'`
Tracing 97156 (/home/agentzh/git/lua-nginx-module/work/nginx/sbin/nginx)...
Hit Ctrl-C to end.
WARNING: Missing unwind data for a module, rerun with 'stap -d /usr/lib64/libc-2.21.so'
WARNING: Missing unwind data for a module, rerun with 'stap -d /opt/luajit21dbg/lib/libluajit-5.1.so.2.1.0'
^C
ngx_http_regex_exec: 2 of 2 are PCRE JITted.
ngx_http_lua_ngx_re_match_helper: 2 of 2 are PCRE JITted.
```

All work as expected. You can try your example on your side.

BTW, below is my Linux system's info:

* Linux kernel 4.4.13
* Systemtap translator/driver (version 3.1/0.161, commit release-3.0-104-gbedfbdce0989 + changes)
* Fedora release 22 (Twenty Two)

**Comment by agentzh** [comment]
@rshriram BTW, such things should go to the `nginx-systemtap-tookit` project instead.

**Comment by rshriram** [comment]
This is weird.. Granted, I have an older kernel (3.16). But I don't understand why things are not working on Ubuntu 14.04. May be its related to this bug in Launchpad where someone reported that PCRE jit was not really enabled. https://bugs.launchpad.net/ubuntu/+source/pcre3/+bug/1285097

I don't think it applies in this case because PCRE is statically compiled into the app. Will investigate more.

Thanks!
