### ISSUE TITLE
unable to return ngx error code other than 500 in balancer_by_lua block

### ISSUE THREAD

**Issue by eahmwah** [openresty/lua-resty-core#64]
From the example given in https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/balancer.md#synopsis

Changing ngx.exit(500) to ngx.exit(503) or another error code still returns 500 (host set to google.com intentionally)

```
upstream backend {
    server 0.0.0.1;   # just an invalid address as a place holder

    balancer_by_lua_block {
        local balancer = require "ngx.balancer"

        -- well, usually we calculate the peer's host and port
        -- according to some balancing policies instead of using
        -- hard-coded values like below
        local host = "google.com"
        local port = 8080

        local ok, err = balancer.set_current_peer(host, port)
        if not ok then
            ngx.log(ngx.ERR, "failed to set the current peer: ", err)
            return ngx.exit(503)
        end
    }

    keepalive 10;  # connection pool
}
```

**Comment by agentzh** [comment]
@eahmwah I'm afraid this is how nginx core's upstream mechanism mandates. We do not have control there. Feel free to prove me wrong though :)

**Comment by eahmwah** [comment]
@agentzh OK understood. Do you think we can rewrite the response code from 500 to 503 after the balancer_by_lua phase?

**Comment by agentzh** [comment]
Try header_filter_by_lua.

**Comment by eahmwah** [comment]
Yes this works. Thanks

**Comment by erankor** [comment]
Bumped into this old issue now... another possible workaround is to do `ngx.exit(-3);` (NGX_BUSY), this error code will propagate up to ngx_http_upstream_connect, which will write 'no live upstreams' to log and fail the request with 502.
