### ISSUE TITLE
balancer_by_lua: cannot return status codes other than 500

### ISSUE THREAD

**Issue by rshriram** [openresty/lua-resty-core#70]
Without going into too much details, 

```lua
return ngx.exit(503)
```
in the balancer_by_lua block. However, I still get HTTP 500. 

Is there a specific API that I need to use?

**Comment by agentzh** [comment]
@rshriram This is the behavior of the nginx upstream facility and we cannot override that in a 3rd-party module.

**Comment by agentzh** [comment]
@rshriram Having said that, you can override it in `header_filter_by_lua*`, BTW.

**Comment by rshriram** [comment]
@agentzh Thanks for the clarification. To summarize, returning anything other than ngx.error, ngx.ok is not possible in a balancer_by_lua context (I went through the code).

the header_filter_by_lua* -- can it work in balancer_by_lua ? I thought the headers are already generated by the time the request reaches balancer by lua stage. And they can't be overridden. If this works, I would love to use it, as I need to set the host header dynamically based on the choice of upstream instance.

**Comment by agentzh** [comment]
@rshriram I mean something like

```nginx
header_filter_by_lua_block {
    ngx.status = 503
}
```

Generated response headers (and also bodies) can be overridden in the output filters, that's what output filters are all about :)

**Comment by agentzh** [comment]
@rshriram You can always use `ngx.ctx` to communicate your own data between different phase handlers anyway.

**Comment by rshriram** [comment]
Would you suggest ngx.var over ngx.ctx, as I thought the latter was costlier.

**Comment by agentzh** [comment]
@rshriram `ngx.var` is much more expensive and much more limited than `ngx.ctx`.

**Comment by agentzh** [comment]
@rshriram `ngx.ctx` is not *that* costly if you do not invoke it in a hot loop. You can always measure the overhead yourself BTW. Just don't be over panic.

**Comment by rshriram** [comment]
😲  ! I thought it was the other way around.. And ended up using ngx.var as much as possible, while avoiding ngx.ctx .. Based on this https://www.cryptobells.com/openresty-performance-ngx-ctx-vs-ngx-shared-dict/ .. and now I see your response in google groups:
```
On Sun, May 1, 2016 at 7:12 PM, Rob Kelledy wrote: 
> "The ngx.ctx lookup requires relatively expensive metamethod calls and it is 
> much slower than explicitly passing per-request data along by your own 
> function arguments. So do not abuse this API for saving your own function 
> arguments because it usually has quite some performance impact." 
> 

Don't worry too much about this paragraph. I added this note just for 
people who want to achieve near-C performance with their Lua code :) 
```

Sigh!

**Comment by agentzh** [comment]
@rshriram Better profile with flame graph tools before trying any optimizations. Otherwise you may very well slow things even further :)
