### ISSUE TITLE
Running tests on macOS fails because poll is not supported

### ISSUE THREAD

**Issue by bungle** [openresty/lua-resty-core#73]
The problem is this line:
https://github.com/openresty/lua-resty-core/blob/master/t/balancer-timeout.t#L19

```
t/balancer-timeout.t ... nginx: [emerg] invalid event type "poll" in /Users/bungle/Sources/vendor/lua-resty-core/t/servroot/conf/nginx.conf:74
```

Is there anything I can do about it on my side?

**Comment by agentzh** [comment]
@bungle You need to specify the `--with-poll_module` option of the `./configure` command while building openresty or nginx.

Well, that test file requires mockeagain which never really works on a mac anyway.

**Comment by bungle** [comment]
Yes, ok. I can live with thia :-).
