### ISSUE TITLE
enable retry in balancer_by_lua_block: need to set proxy_next_upstream_tries

### ISSUE THREAD

**Issue by fongx** [openresty/lua-resty-core#90]
hello,  I find, in order to enable the retry,  it needs to explicitly  set the [proxy_next_upstream_tries](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream_tries) directive to a value greater than the default value, zero.  I think it's a bug or at least it's incompatible with the original upstream failover policy.  Because the document says the default zero value indicates that nginx won't limit the retry times other than disable the retry.  If it's by design, its better to make it clearly in the document.

**Comment by agentzh** [comment]
@fongx Will you try the latest master branch of lua-nginx-module?

**Comment by fongx** [comment]
I have the issue in the latest release openresty-1.11.2.2.tar.gz of lua-nginx-module but not test the latest master branch. Do you have merged any changes for this to the master branch since v1.11.2.2?

PS: sorry for the close and reopen by a mistaken click

**Comment by agentzh** [comment]
@fongx IIRC, there is a related fix in the master. Why don't you try it out and/or check out the commit log history?

**Comment by fongx** [comment]
I checkout the latest master and install it on a new machine. But it's weired, the problem seems unresolved. Yes, I find the patch have been applied at [853](https://github.com/openresty/lua-nginx-module/pull/853). Maybe I still miss something else. I will check more and then come back.

**Comment by fongx** [comment]
BINGO. It's fixed in the latest master branch. Thanks.
